// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gltdguxpanwybybgxayq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsdGRndXhwYW53eWJ5Ymd4YXlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNjk1NDEsImV4cCI6MjA3MDg0NTU0MX0.RUJ7KO3JaexZzwQSIG-CFZQNtAwX9Y_tDqusH-UWPaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});